# Copyright 2025 LiangNing7 <LiangNing7@gmail.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/LiangNing7/zenith.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zn-apiserver # 资源标签
  name: zn-apiserver # 资源名称
spec:
  replicas: 2 # 副本数
  progressDeadlineSeconds: 10
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: zn-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zn-apiserver
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - zn-apiserver
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - /opt/zenith/bin/zn-apiserver.yaml
        - --config=/etc/zenith/zn-apiserver.yaml
        image: "onexstack/zn-apiserver-amd64:v1.0.0"
        name: zn-apiserver
        ports:
        - containerPort: 8443
          name: secure
          protocol: TCP
        - containerPort: 8080
          name: insecure
          protocol: TCP
        - containerPort: 9090
          name: rpc
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/zenith/zn-apiserver.yaml
          name: zenith
          subPath: zn-apiserver.yaml
        - mountPath: /etc/zenith/cert
          name: zenith-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
            {}
      terminationGracePeriodSeconds: 5
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: zn-apiserver.yaml
            path: zn-apiserver.yaml
          name: zn-apiserver
        name: zenith
      - configMap:
          defaultMode: 420
          name: zenith-cert
        name: zenith-cert
